service: nest-serverless-example


plugins:
  - serverless-offline
provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs20.x

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}